using System.Diagnostics;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using static AssetTool.UEdGraphPin;

namespace AssetTool
{
    [JsonAsset("EdGraphPin")]
    [DebuggerDisplay("[{ResolveType}] {PinGuid} {PinName}")]
    public class UEdGraphPin : UObject, ITransferableAutoCheck
    {
        public const string TypeName = "EdGraphPin";

        [JsonIgnore] public UEdGraphNode Owner;
        [JsonIgnore] public EPinResolveType ResolveType;
        [JsonIgnore] public bool SerializeCalled;

        #region SerializePin
        public FBool? bNullPtr;
        public TRef LocalOwningNode;
        public FGuid? PinGuid;
        #endregion

        #region Part 2
        public TRef OwningNode;
        public FGuid? PinId;
        public FName PinName;
        public FString PinNameStr;
        public FText PinFriendlyName;
        public Int32? SourceIndex;
        public FString PinToolTip;
        public EEdGraphPinDirection Direction;

        public FEdGraphPinType PinType;

        public FString DefaultValue;
        public FString AutogeneratedDefaultValue;
        public FObjectPtr DefaultObject;
        public FText DefaultTextValue;

        public NonOwningNodePin LinkedTo;
        public NonOwningNodePin SubPins;

        public ParentPinWrapper ParentPin;

        public UEdGraphPin ReferencePassThroughConnection;

        public FGuid? PersistentGuid;
        public UInt32? BitField;
        #endregion

        public enum EPinResolveType : UInt32
        {
            OwningNode,
            LinkedTo,
            SubPins,
            ParentPin,
            ReferencePassThroughConnection
        };

        [Location("void UEdGraphPin::SerializePinArray(FArchive& Ar, TArray<UEdGraphPin*>& ArrayRef, UEdGraphPin* RequestingPin, EPinResolveType ResolveType)")]
        public static void SerializePinArray(Transfer transfer, ref List<UEdGraphPin> ArrayRef, EPinResolveType ResolveType, UEdGraphNode node)
        {
            transfer.Resize(ref ArrayRef, true);
            for (int i = 0; i < ArrayRef.Count; i++)
            {
                FBool bNullPtr = ArrayRef[i]?.bNullPtr ?? new FBool();
                transfer.Move(ref bNullPtr);
                if (!bNullPtr)
                {
                    ArrayRef[i] ??= new();
                    ArrayRef[i].Owner = node;
                    ArrayRef[i].ResolveType = ResolveType;
                    SerializePin(transfer, ArrayRef[i]);
                }
            }
        }

        [Location("bool UEdGraphPin::SerializePin(FArchive& Ar, UEdGraphPin*& PinRef, int32 ArrayIdx, UEdGraphPin* RequestingPin, EPinResolveType ResolveType, TArray<UEdGraphPin*>& OldPins)")]
        public static void SerializePin(Transfer transfer, UEdGraphPin PinRef)
        {
            transfer.Move(ref PinRef.LocalOwningNode);
            transfer.Move(ref PinRef.PinGuid);
            if (PinRef.ResolveType == EPinResolveType.OwningNode)
            {
                transfer.Move(ref PinRef, (x) => x.Serialize(transfer));
            }
        }

        [Location("bool UEdGraphPin::Serialize(FArchive& Ar)")]
        public UEdGraphPin Serialize(Transfer transfer)
        {
            SerializeCalled = true;
            //long[] offsets = [transfer.Position, 0];

            transfer.Move(ref OwningNode);
            transfer.Move(ref PinId);

            if (transfer.Supports.PinsStoreFName)
                transfer.Move(ref PinName);
            else
                transfer.Move(ref PinNameStr);

            PinFriendlyName = PinFriendlyName is null ? new FText() { HistoryType = (ETextHistoryType)(-1) } : PinFriendlyName;
            if (!transfer.GlobalObjects.IsFilterEditorOnly())
                transfer.Move(ref PinFriendlyName);
            PinFriendlyName = PinFriendlyName.IsNull ? null : PinFriendlyName;

            if (transfer.Supports.EdGraphPinSourceIndex)
                transfer.Move(ref SourceIndex);

            transfer.Move(ref PinToolTip);
            transfer.MoveEnum(ref Direction);

            transfer.Move(ref PinType);

            transfer.Move(ref DefaultValue);
            transfer.Move(ref AutogeneratedDefaultValue);

            if (transfer.IsReading)
            {
                transfer.Move(ref DefaultObject);
                DefaultObject = DefaultObject.Index.Index == 0 ? null : DefaultObject;
            }
            else
            {
                int index = DefaultObject?.Index.Index ?? 0;
                transfer.Move(ref index);
            }

            DefaultTextValue = DefaultTextValue is null ? new FText() { HistoryType = (ETextHistoryType)(-1) } : DefaultTextValue;
            transfer.Move(ref DefaultTextValue);
            DefaultTextValue = DefaultTextValue.IsNull ? null : DefaultTextValue;

            LinkedTo ??= new();
            UEdGraphPin.SerializePinArray(transfer, ref LinkedTo.List, EPinResolveType.LinkedTo, Owner);
            LinkedTo = LinkedTo.List.Count == 0 ? null : LinkedTo;

            SubPins ??= new();
            UEdGraphPin.SerializePinArray(transfer, ref SubPins.List, EPinResolveType.SubPins, Owner);
            SubPins = SubPins.List.Count == 0 ? null : SubPins;

            FBool ParentPinIsNull = ParentPin is null;
            transfer.Move(ref ParentPinIsNull);
            if (!ParentPinIsNull)
            {
                ParentPin ??= new();
                ParentPin.ParentPin.ResolveType = EPinResolveType.ParentPin;
                SerializePin(transfer, ParentPin.ParentPin);
            }

            FBool ReferencePassThroughConnectionIsNull = ReferencePassThroughConnection is null;
            transfer.Move(ref ReferencePassThroughConnectionIsNull);
            if (!ReferencePassThroughConnectionIsNull)
            {
                ReferencePassThroughConnection ??= new();
                ReferencePassThroughConnection.ResolveType = EPinResolveType.ReferencePassThroughConnection;
                SerializePin(transfer, ReferencePassThroughConnection);
            }

            if (!transfer.GlobalObjects.IsFilterEditorOnly())
            {
                transfer.Move(ref PersistentGuid);
                transfer.Move(ref BitField);
            }

            //#region Remove
            //if (transfer.IsReading)
            //{
            //    offsets[1] = transfer.Position;
            //    AppConfig.DebugCheckMember = true;
            //    this.AutoCheck(transfer, "UEdGraphPin", transfer.Stream, offsets);
            //    AppConfig.DebugCheckMember = false;
            //}
            //#endregion

            return this;
        }

        public ITransferable MoveAutoCheck(Transfer transfer)
        {
            return Serialize(transfer);
        }

        public override string ToString()
        {
            StringBuilder builder = new();
            if (ResolveType is EPinResolveType.LinkedTo or EPinResolveType.SubPins)
            {
                builder.Append($"{LocalOwningNode} {PinGuid}");
            }
            else
            {
                builder.Append(Direction == EEdGraphPinDirection.EGPD_Input ? "input-pin " : "output-pin ");
                builder.AppendNonNull("Type((`{0}`)) ", PinType);
                builder.AppendNonNull("Name(`{0}`) ", PinName);
                builder.AppendNonNull("PinFriendlyName((`{0}`)) ", PinFriendlyName?.ToStringOrObject());
                builder.AppendNonNull("Id(`{0} {1}`) ", LocalOwningNode, PinGuid);
                builder.AppendNonNull("LinkedTo(`{0}`) ", LinkedTo);
                builder.AppendNonNull("SubPins(`{0}`) ", SubPins);
                builder.AppendNonNull("ToolTip(`{0}`) ", PinToolTip);
                builder.AppendNonNull("DefaultValue(`{0}`) ", DefaultValue);
                builder.AppendNonNull("AutogeneratedDefaultValue(`{0}`) ", AutogeneratedDefaultValue);
                builder.AppendNonNull("BitField(`{0}`) ", BitField);
                builder.AppendNonNull("DefaultObject(`{0}`) ", DefaultObject);
            }
            return builder.ToString();
        }

        public static UEdGraphPin FromString(string str)
        {
            UEdGraphPin result = new();
            result.Direction = str[0..str.IndexOf(' ')] == "input-pin" ? EEdGraphPinDirection.EGPD_Input : EEdGraphPinDirection.EGPD_Output;
            result.PinType = str.GetNonNull("Type((`{0}`))", x => FEdGraphPinType.FromString(x));
            if (result.PinType is { })
            {
                result.PinName = str.GetNonNull("Name(`{0}`)", x => new FName(x));
                result.PinFriendlyName = str.GetNonNull("PinFriendlyName((`{0}`))", x => FText.FromStringOrObject(x));
                result.LocalOwningNode = result.OwningNode = str.GetNonNull("Id(`{0}`)", x => TRef.FromString(x[0..x.IndexOf(' ')]));
                result.PinGuid = result.PinId = str.GetNonNull("Id(`{0}`)", x => new FGuid(x[x.IndexOf(' ')..]));
                result.LinkedTo = str.GetNonNull("LinkedTo(`{0}`)", x => NonOwningNodePin.FromString(x, EPinResolveType.LinkedTo));
                result.SubPins = str.GetNonNull("SubPins(`{0}`)", x => NonOwningNodePin.FromString(x, EPinResolveType.SubPins));
                result.PinToolTip = str.GetNonNull("ToolTip(`{0}`)", x => new FString(x));
                result.DefaultValue = str.GetNonNull("DefaultValue(`{0}`)", x => new FString(x));
                result.AutogeneratedDefaultValue = str.GetNonNull("AutogeneratedDefaultValue(`{0}`)", x => new FString(x));
                result.BitField = str.GetNonNull("BitField(`{0}`)", x => uint.Parse(x));
                result.DefaultObject = str.GetNonNull("DefaultObject(`{0}`)", x => FObjectPtr.FromString(x));
            }
            else
            {
                result.LocalOwningNode = result.OwningNode = TRef.FromString(str.Split(' ')[1]);
                result.PinGuid = result.PinId = new FGuid(str.Split(' ')[2]);
            }
            return result;
        }
    }

    #region LinkedTo JsonConverter
    public class NonOwningNodePin
    {
        public List<UEdGraphPin> List = [];

        public override string ToString() => string.Join(" | ", List.Select(x => $"{((UEdGraphPin)x).LocalOwningNode} {((UEdGraphPin)x).PinGuid}"));

        public static NonOwningNodePin FromString(string str, EPinResolveType resolveType)
        {
            NonOwningNodePin result = new();
            string[] parts = str.Split(" | ");
            result.List = [];
            foreach (var part in parts)
            {
                var item = new UEdGraphPin
                {
                    ResolveType = resolveType,
                    LocalOwningNode = TRef.FromString(part[0..part.IndexOf(' ')]),
                    PinGuid = new FGuid(part.Split(' ')[1])
                };
                result.List.Add(item);
            }
            return result;
        }
    }

    public class LinkedToWrapperJsonConverter : JsonConverter<NonOwningNodePin>
    {
        public override NonOwningNodePin Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string text = reader.GetString();
            if (text.Length == 0)
            {
                return new();
            }
            NonOwningNodePin list = new();
            var lines = text.Split(" | ");
            foreach (var line in lines)
            {
                var v = line.Split(' ');
                var item = new UEdGraphPin
                {
                    LocalOwningNode = new TRef { ExportIndex = Int32.Parse(v[0]) },
                    PinGuid = new FGuid(v[1])
                };
                list.List.Add(item);
            }
            return list;
        }

        public override void Write(Utf8JsonWriter writer, NonOwningNodePin value, JsonSerializerOptions options)
        {
            var lines = string.Join(" | ", value.List.Select(x => $"{((UEdGraphPin)x).LocalOwningNode.ExportIndex} {((UEdGraphPin)x).PinGuid}"));
            if (lines.Length == 0)
                writer.WriteNullValue();
            else
                writer.WriteStringValue(lines);
        }
    }
    #endregion

    #region ParentPin JsonConverter
    public class ParentPinWrapper
    {
        public UEdGraphPin ParentPin = new();
    }

    public class ParentPinWrapperJsonConverter : JsonConverter<ParentPinWrapper>
    {
        public override ParentPinWrapper Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            ReadOnlySpan<char> span = reader.GetString().AsSpan();

            Int32 exportIndex = Int32.Parse(span.Slice(0, span.IndexOf(' ')));
            string guid = span.Slice(span.IndexOf(' ') + 1).ToString();

            return new() { ParentPin = new() { LocalOwningNode = new() { ExportIndex = exportIndex }, PinGuid = new FGuid(guid) } };
        }

        public override void Write(Utf8JsonWriter writer, ParentPinWrapper value, JsonSerializerOptions options)
        {
            writer.WriteStringValue($"{value.ParentPin.LocalOwningNode.ExportIndex} {value.ParentPin.PinGuid}");
        }
    }
    #endregion

    public class UEdGraphPinJsonConverter : JsonConverter<UEdGraphPin>
    {
        public override UEdGraphPin Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return UEdGraphPin.FromString(reader.GetString());
        }

        public override void Write(Utf8JsonWriter writer, UEdGraphPin value, JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString());
        }
    }
}
