namespace AssetTool
{
    public enum RT_PAYLOAD_TYPE : uint32
    {
        RT_PAYLOAD_TYPE_MINIMAL = (1 << 0),
        RT_PAYLOAD_TYPE_DEFAULT = (1 << 1),
        RT_PAYLOAD_TYPE_RAYTRACING_MATERIAL = (1 << 2),
        RT_PAYLOAD_TYPE_RAYTRACING_DEBUG = (1 << 3),
        RT_PAYLOAD_TYPE_DEFERRED = (1 << 4),
        RT_PAYLOAD_TYPE_PATHTRACING_MATERIAL = (1 << 5),
        RT_PAYLOAD_TYPE_LUMEN_MINIMAL = (1 << 6),
        RT_PAYLOAD_TYPE_VFX = (1 << 7),
        RT_PAYLOAD_TYPE_DECALS = (1 << 8),
        RT_PAYLOAD_TYPE_SPARSE_VOXEL = (1 << 9),
        RT_PAYLOAD_TYPE_GPULIGHTMASS = (1 << 10)
    }

    public enum ERayTracingPayloadType : uint32
    {
        None = 0,
        Minimal = RT_PAYLOAD_TYPE.RT_PAYLOAD_TYPE_MINIMAL,
        Default = RT_PAYLOAD_TYPE.RT_PAYLOAD_TYPE_DEFAULT,
        RayTracingMaterial = RT_PAYLOAD_TYPE.RT_PAYLOAD_TYPE_RAYTRACING_MATERIAL,
        RayTracingDebug = RT_PAYLOAD_TYPE.RT_PAYLOAD_TYPE_RAYTRACING_DEBUG,
        Deferred = RT_PAYLOAD_TYPE.RT_PAYLOAD_TYPE_DEFERRED,
        PathTracingMaterial = RT_PAYLOAD_TYPE.RT_PAYLOAD_TYPE_PATHTRACING_MATERIAL,
        LumenMinimal = RT_PAYLOAD_TYPE.RT_PAYLOAD_TYPE_LUMEN_MINIMAL,
        VFX = RT_PAYLOAD_TYPE.RT_PAYLOAD_TYPE_VFX,
        Decals = RT_PAYLOAD_TYPE.RT_PAYLOAD_TYPE_DECALS,
        SparseVoxel = RT_PAYLOAD_TYPE.RT_PAYLOAD_TYPE_SPARSE_VOXEL,
        GPULightmass = RT_PAYLOAD_TYPE.RT_PAYLOAD_TYPE_GPULIGHTMASS,
    }
}
