namespace AssetTool
{
    [JsonAsset("K2Node_ActorBoundEvent")] public class UK2Node_ActorBoundEvent : UK2Node_Event { }
    ///[JsonAsset("K2Node_AddComponent")] public class UK2Node_AddComponent : UK2Node_CallFunction { }
    [JsonAsset("K2Node_AddComponentBy")] public class UK2Node_AddComponentBy : UK2Node_ConstructObjectFromClass { }
    [JsonAsset("K2Node_AddDelegate")] public class UK2Node_AddDelegate : UK2Node_BaseMCDelegate { }
    [JsonAsset("K2Node_AssignDelegate")] public class UK2Node_AssignDelegate : UK2Node_AddDelegate { }
    ///[JsonAsset("K2Node_AssignmentStatement")] public class UK2Node_AssignmentStatement : UK2Node { }
    [JsonAsset("K2Node_AsyncAction")] public class UK2Node_AsyncAction : UK2Node_BaseAsyncTask { }
    ///[JsonAsset("K2Node_BaseAsyncTask")] public class UK2Node_BaseAsyncTask : UK2Node { }
    [JsonAsset("K2Node_BaseMCDelegate")] public class UK2Node_BaseMCDelegate : UK2Node { }
    [JsonAsset("K2Node_BitmaskLiteral")] public class UK2Node_BitmaskLiteral : UK2Node { }
    ///[JsonAsset("K2Node_BreakStruct")] public class UK2Node_BreakStruct : UK2Node_StructMemberGet { }
    ///[JsonAsset("K2Node_CallArrayFunction")] public class UK2Node_CallArrayFunction : UK2Node_CallFunction { }
    [JsonAsset("K2Node_CallDataTableFunction")] public class UK2Node_CallDataTableFunction : UK2Node_CallFunction { }
    [JsonAsset("K2Node_CallDelegate")] public class UK2Node_CallDelegate : UK2Node_BaseMCDelegate { }
    ///[JsonAsset("K2Node_CallFunction")] public class UK2Node_CallFunction : UK2Node { }
    [JsonAsset("K2Node_CallFunctionOnMember")] public class UK2Node_CallFunctionOnMember : UK2Node_CallFunction { }
    ///[JsonAsset("K2Node_CallMaterialParameterCollectionFunction")] public class UK2Node_CallMaterialParameterCollectionFunction : UK2Node_CallFunction { }
    ///[JsonAsset("K2Node_CallParentFunction")] public class UK2Node_CallParentFunction : UK2Node_CallFunction { }
    [JsonAsset("K2Node_CastByteToEnum")] public class UK2Node_CastByteToEnum : UK2Node { }
    [JsonAsset("K2Node_ClassDynamicCast")] public class UK2Node_ClassDynamicCast : UK2Node_DynamicCast { }
    [JsonAsset("K2Node_ClearDelegate")] public class UK2Node_ClearDelegate : UK2Node_BaseMCDelegate { }
    ///[JsonAsset("K2Node_CommutativeAssociativeBinaryOperator")] public class UK2Node_CommutativeAssociativeBinaryOperator : UK2Node_CallFunction { }
    [JsonAsset("K2Node_ComponentBoundEvent")] public class UK2Node_ComponentBoundEvent : UK2Node_Event { }
    ///[JsonAsset("K2Node_Composite")] public class UK2Node_Composite : UK2Node_Tunnel { }
    [JsonAsset("K2Node_ConstructObjectFrom")] public class UK2Node_ConstructObjectFrom : UK2Node { }
    [JsonAsset("K2Node_ConvertAsset")] public class UK2Node_ConvertAsset : UK2Node { }
    [JsonAsset("K2Node_Copy")] public class UK2Node_Copy : UK2Node { }
    [JsonAsset("K2Node_CreateDelegate")] public class UK2Node_CreateDelegate : UK2Node { }
    ///[JsonAsset("K2Node_CustomEvent")] public class UK2Node_CustomEvent : UK2Node_Event { }
    [JsonAsset("K2Node_Dead")] public class UK2Node_Dead : UK2Node { }
    [JsonAsset("K2Node_DelegateSet")] public class UK2Node_DelegateSet : UK2Node { }
    [JsonAsset("K2Node_DoOnceMultiInput")] public class UK2Node_DoOnceMultiInput : UK2Node { }
    ///[JsonAsset("K2Node_DynamicCast")] public class UK2Node_DynamicCast : UK2Node { }
    [JsonAsset("K2Node_EaseFunction")] public class UK2Node_EaseFunction : UK2Node { }
    ///[JsonAsset("K2Node_EditablePinBase")] public class UK2Node_EditablePinBase : UK2Node { }
    [JsonAsset("K2Node_EnumEquality")] public class UK2Node_EnumEquality : UK2Node { }
    [JsonAsset("K2Node_EnumInequality")] public class UK2Node_EnumInequality : UK2Node_EnumEquality { }
    [JsonAsset("K2Node_EnumLiteral")] public class UK2Node_EnumLiteral : UK2Node { }
    ///[JsonAsset("K2Node_Event")] public class UK2Node_Event : UK2Node_EditablePinBase { }
    ///[JsonAsset("K2Node_ExecutionSequence")] public class UK2Node_ExecutionSequence : UK2Node { }
    [JsonAsset("K2Node_ForEachElementInEnum")] public class UK2Node_ForEachElementInEnum : UK2Node { }
    [JsonAsset("K2Node_FormatText")] public class UK2Node_FormatText : UK2Node { }
    ///[JsonAsset("K2Node_FunctionEntry")] public class UK2Node_FunctionEntry : UK2Node_FunctionTerminator { }
    ///[JsonAsset("K2Node_FunctionResult")] public class UK2Node_FunctionResult : UK2Node_FunctionTerminator { }
    ///[JsonAsset("K2Node_FunctionTerminator")] public class UK2Node_FunctionTerminator : UK2Node_EditablePinBase { }
    [JsonAsset("K2Node_GenericCreateObject")] public class UK2Node_GenericCreateObject : UK2Node_ConstructObjectFromClass { }
    ///[JsonAsset("K2Node_GetArrayItem")] public class UK2Node_GetArrayItem : UK2Node { }
    [JsonAsset("K2Node_GetClassDefaults")] public class UK2Node_GetClassDefaults : UK2Node { }
    ///[JsonAsset("K2Node_GetDataTableRow")] public class UK2Node_GetDataTableRow : UK2Node { }
    [JsonAsset("K2Node_GetEnumeratorName")] public class UK2Node_GetEnumeratorName : UK2Node { }
    [JsonAsset("K2Node_GetEnumeratorNameAsString")] public class UK2Node_GetEnumeratorNameAsString : UK2Node_GetEnumeratorName { }
    [JsonAsset("K2Node_GetInputAxisKeyValue")] public class UK2Node_GetInputAxisKeyValue : UK2Node_CallFunction { }
    [JsonAsset("K2Node_GetInputAxisValue")] public class UK2Node_GetInputAxisValue : UK2Node_CallFunction { }
    [JsonAsset("K2Node_GetInputVectorAxisValue")] public class UK2Node_GetInputVectorAxisValue : UK2Node_GetInputAxisKeyValue { }
    [JsonAsset("K2Node_GetNumEnumEntries")] public class UK2Node_GetNumEnumEntries : UK2Node { }
    ///[JsonAsset("K2Node_GetSubsystem")] public class UK2Node_GetSubsystem : UK2Node { }
    ///[JsonAsset("K2Node_GetSubsystemFromPC")] public class UK2Node_GetSubsystemFromPC : UK2Node_GetSubsystem { }
    [JsonAsset("K2Node_GetEngineSubsystem")] public class UK2Node_GetEngineSubsystem : UK2Node_GetSubsystem { }
    [JsonAsset("K2Node_GetEditorSubsystem")] public class UK2Node_GetEditorSubsystem : UK2Node_GetSubsystem { }
    ///[JsonAsset("K2Node_IfThenElse")] public class UK2Node_IfThenElse : UK2Node { }
    [JsonAsset("K2Node_InputAction")] public class UK2Node_InputAction : UK2Node { }
    [JsonAsset("K2Node_InputActionEvent")] public class UK2Node_InputActionEvent : UK2Node_Event { }
    [JsonAsset("K2Node_InputAxisEvent")] public class UK2Node_InputAxisEvent : UK2Node_Event { }
    [JsonAsset("K2Node_InputAxisKeyEvent")] public class UK2Node_InputAxisKeyEvent : UK2Node_Event { }
    [JsonAsset("K2Node_InputKey")] public class UK2Node_InputKey : UK2Node { }
    [JsonAsset("K2Node_InputKeyEvent")] public class UK2Node_InputKeyEvent : UK2Node_Event { }
    [JsonAsset("K2Node_InputTouch")] public class UK2Node_InputTouch : UK2Node { }
    [JsonAsset("K2Node_InputTouchEvent")] public class UK2Node_InputTouchEvent : UK2Node_Event { }
    [JsonAsset("K2Node_InputVectorAxisEvent")] public class UK2Node_InputVectorAxisEvent : UK2Node_InputAxisKeyEvent { }
    ///[JsonAsset("K2Node_Knot")] public class UK2Node_Knot : UK2Node { }
    [JsonAsset("K2Node_Literal")] public class UK2Node_Literal : UK2Node { }
    ///[JsonAsset("K2Node_LoadAsset")] public class UK2Node_LoadAsset : UK2Node { }
    ///[JsonAsset("K2Node_LoadAsset")] public class UK2Node_LoadAsset : UK2Node_LoadAsset { }
    [JsonAsset("DEPRECATED_K2Node_LocalVariable")] public class UDEPRECATED_K2Node_LocalVariable : UK2Node_TemporaryVariable { }
    ///[JsonAsset("K2Node_MacroInstance")] public class UK2Node_MacroInstance : UK2Node_Tunnel { }
    ///[JsonAsset("K2Node_MakeArray")] public class UK2Node_MakeArray : UK2Node_MakeContainer { }
    ///[JsonAsset("K2Node_MakeContainer")] public class UK2Node_MakeContainer : UK2Node { }
    [JsonAsset("K2Node_MakeMap")] public class UK2Node_MakeMap : UK2Node_MakeContainer { }
    [JsonAsset("K2Node_MakeSet")] public class UK2Node_MakeSet : UK2Node_MakeContainer { }
    ///[JsonAsset("K2Node_MakeStruct")] public class UK2Node_MakeStruct : UK2Node_StructMemberSet { }
    [JsonAsset("K2Node_MakeVariable")] public class UK2Node_MakeVariable : UK2Node { }
    [JsonAsset("K2Node_MathExpression")] public class UK2Node_MathExpression : UK2Node_Composite { }
    ///[JsonAsset("K2Node_Message")] public class UK2Node_Message : UK2Node_CallFunction { }
    [JsonAsset("K2Node_MultiGate")] public class UK2Node_MultiGate : UK2Node_ExecutionSequence { }
    ///[JsonAsset("K2Node_PromotableOperator")] public class UK2Node_PromotableOperator : UK2Node_CallFunction { }
    [JsonAsset("K2Node_PureAssignmentStatement")] public class UK2Node_PureAssignmentStatement : UK2Node { }
    [JsonAsset("K2Node_RemoveDelegate")] public class UK2Node_RemoveDelegate : UK2Node_BaseMCDelegate { }
    ///[JsonAsset("K2Node_Select")] public class UK2Node_Select : UK2Node { }
    ///[JsonAsset("K2Node_Self")] public class UK2Node_Self : UK2Node { }
    [JsonAsset("K2Node_SetFieldsInStruct")] public class UK2Node_SetFieldsInStruct : UK2Node_MakeStruct { }
    [JsonAsset("K2Node_SetVariableOnPersistentFrame")] public class UK2Node_SetVariableOnPersistentFrame : UK2Node { }
    [JsonAsset("K2Node_SpawnActor")] public class UK2Node_SpawnActor : UK2Node { }
    [JsonAsset("K2Node_SpawnActorFrom")] public class UK2Node_SpawnActorFrom : UK2Node_ConstructObjectFromClass { }
    ///[JsonAsset("K2Node_StructMemberGet")] public class UK2Node_StructMemberGet : UK2Node_StructOperation { }
    ///[JsonAsset("K2Node_StructMemberSet")] public class UK2Node_StructMemberSet : UK2Node_StructOperation { }
    ///[JsonAsset("K2Node_StructOperation")] public class UK2Node_StructOperation : UK2Node_Variable { }
    ///[JsonAsset("K2Node_Switch")] public class UK2Node_Switch : UK2Node { }
    ///[JsonAsset("K2Node_SwitchEnum")] public class UK2Node_SwitchEnum : UK2Node_Switch { }
    [JsonAsset("K2Node_SwitchInteger")] public class UK2Node_SwitchInteger : UK2Node_Switch { }
    [JsonAsset("K2Node_SwitchName")] public class UK2Node_SwitchName : UK2Node_Switch { }
    [JsonAsset("K2Node_SwitchString")] public class UK2Node_SwitchString : UK2Node_Switch { }
    ///[JsonAsset("K2Node_TemporaryVariable")] public class UK2Node_TemporaryVariable : UK2Node { }
    [JsonAsset("K2Node_Timeline")] public class UK2Node_Timeline : UK2Node { }
    ///[JsonAsset("K2Node_Tunnel")] public class UK2Node_Tunnel : UK2Node_EditablePinBase { }
    [JsonAsset("K2Node_TunnelBoundary")] public class UK2Node_TunnelBoundary : UK2Node { }
    ///[JsonAsset("K2Node_Variable")] public class UK2Node_Variable : UK2Node { }
    ///[JsonAsset("K2Node_VariableGet")] public class UK2Node_VariableGet : UK2Node_Variable { }
    ///[JsonAsset("K2Node_VariableSet")] public class UK2Node_VariableSet : UK2Node_Variable { }
    [JsonAsset("K2Node_VariableSetRef")] public class UK2Node_VariableSetRef : UK2Node { }
    [JsonAsset("K2Node_ConstructObjectFromClass")] public class UK2Node_ConstructObjectFromClass : UK2Node { }
    [JsonAsset("K2Node_SpawnActorFromClass")] public class UK2Node_SpawnActorFromClass : UK2Node_ConstructObjectFromClass { }
}
